name: Build and deploy Spring Boot app to Azure Web App

on:
  push:
    branches:
      - spring-migration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: spring-jar
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: spring-jar
          path: target

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <SEU_NOME_DO_WEBAPP>      # ex: alertas-urbanos-app
          images: |
            $(docker build --tag azurecr.io/${{ github.repository }}:latest .)
